routes/web.php
<?php

use App\Http\Controllers\MainResultController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\FormController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\Admin\NoticeController;
use App\Http\Controllers\Website\HomeController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Website\ContactMessageController;
use Spatie\MediaLibrary\MediaCollections\Models\Media as MediaAlias;

// cache clear
Route::get('reboot', function () {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    dd('Done');
});
Route::get('storageLink', function () {
    Artisan::call('storage:link');
    dd('Done');
});
Route::get('migrate', function () {
    Artisan::call('migrate');
    dd('Done');
});

Route::get('migrate-seed', function () {
    Artisan::call('migrate:fresh --seed');
    dd('Done');
});

Route:: middleware('web')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('result/search',[HomeController::class,'result'])->name('result.search');
});

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function () {
    Route::view('/', 'dashboard.dashboard')->name('dashboard');
    Route::resource('user', UserController::class);
    Route::resource('faq', FaqController::class)->except('index', 'show');
    Route::resource('contact-message', ContactMessageController::class)->except(['show', 'create', 'edit', 'update']);
    Route::resource('notice', NoticeController::class)->except('show');
    Route::resource('form', FormController::class)->except('show');
    Route::resource('student', StudentController::class)->except('show');
    Route::resource('subject', SubjectController::class)->except('show');
    Route::resource('department', DepartmentController::class)->except('show');
    Route::resource('result', ResultController::class)->except('show');
    Route::get('result/particular', [ResultController::class, 'particular'])->name('result.particular');
    Route::post('result/particularData',[ResultController::class,'particularData'])->name('result.particularData');
    Route::post('result/dataStore',[ResultController::class,'dataStore'])->name('result.dataStore');

//    Main Results
    Route::get('mainResult',[MainResultController::class,'index'])->name('mainResult.index');
    Route::get('mainResult/search',[MainResultController::class,'search'])->name('mainResult.search');
    Route::post('mainResult/result',[MainResultController::class,'result'])->name('mainResult.result');

    Route::get('change_password', [UserController::class, 'change_password'])->name('change_password');
    Route::get('settings/company_settings', [SettingController::class, 'editCompanySetting'])->name('company.edit');
    Route::post('settings/company_setting', [SettingController::class, 'updateCompanySetting'])->name('company.update');

    Route::delete('remove-media/{media}', function (MediaAlias $media) {
        $media->delete();
        return back()->with('success', 'Media successfully deleted.');
    })->name('remove-media');

    // Role Permission
    Route::resource('developer/permission', PermissionController::class)->only('index', 'store');
    Route::get('role/assign', [RoleController::class, 'roleAssign'])->name('role.assign');
    Route::post('role/assign', [RoleController::class, 'storeAssign'])->name('store.assign');
    Route::resource('role', RoleController::class);
});

app/Models/Student.php
<?php

namespace App\Models;

use App\Models\Shift;
use App\Models\Result;
use App\Models\Subject;
use App\Models\Section;
use App\Models\Semester;
use App\Models\Department;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Student extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'roll',
        'reg',
        'session',
        'section_id',
        'shift_id',
        'semester_id',
        'department_id'
    ];

    public function semester()
    {
        return $this->belongsTo(Semester::class);
    }
    public function shift()
    {
        return $this->belongsTo(Shift::class);
    }
    public function section()
    {
        return $this->belongsTo(Section::class);
    }
    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    public function results()
    {
        return $this->hasMany(Result::class);
    }

    public function mainResults()
    {
        return $this->hasMany(MainResult::class);
    }

    public function semesterSubject(){
        return $this->hasManyThrough(Subject::class,Semester::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use App\Models\Section;
use App\Models\Semester;
use App\Models\Shift;
use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    public function index()
    {
        $this->checkPermission('student.access');

        $students = Student::with(['department','semester','section','shift'])->paginate($this->itemPerPage);
        $this->putSL($students);
        return view('dashboard.student.index', compact('students'));
    }

    public function create()
    {
        $this->checkPermission('student.create');

        $semesters=Semester::get();
        $sections=Section::get();
        $shifts=Shift::get();
        $departments=Department::get();

        return view('dashboard.student.create',compact('semesters','sections','shifts','departments'));
    }

    public function store(Request $request)
    {
        // dd($request->all());
        $this->checkPermission('student.create');

        $validated = $request->validate([
            'name'              => ['required', 'string', 'max:255'],
            'roll'              => ['required', 'integer'],
            'reg'               => ['required', 'integer'],
            'session'           => ['required', 'string'],
            'section_id'        => ['required', 'integer'],
            'shift_id'          => ['required', 'integer'],
            'semester_id'       => ['required', 'integer'],
            'department_id'     => ['required', 'integer'],
        ]);

        Student::create($validated);

        return redirect()->route('student.index')->with('success', 'Student Created Successfully.');
    }

    public function edit(Student $student)
    {
        $this->checkPermission('student.edit');
        // dd($student);

        $semesters=Semester::get();
        $sections=Section::get();
        $shifts=Shift::get();
        $departments=Department::get();
        // dd($students);


        return view('dashboard.student.edit', compact('student','semesters','sections','shifts','departments'));
    }

    public function update(Request $request, Student $student)
    {
        $this->checkPermission('student.edit');

        $validated = $request->validate([
            'name'              => ['required', 'string', 'max:255'],
            'roll'              => ['required', 'integer'],
            'reg'               => ['required', 'integer'],
            'session'           => ['required', 'string'],
            'section_id'        => ['required', 'integer'],
            'shift_id'          => ['required', 'integer'],
            'semester_id'       => ['required', 'integer'],
            'department_id'     => ['required', 'integer'],
        ]);

        $student->update($validated);

        return redirect()->route('student.index')->with('success', 'Student updated successfully.');
    }

    public function destroy(Student $student)
    {
        $this->checkPermission('student.delete');

        $student->delete();
        return back()->with('success', 'Student deleted successfully.');
    }
}

resources/views/dashboard/student/create.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="card card-custom card-sticky" id="kt_page_sticky_card">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">
        Add New Student
      </h3>
    </div>
    <div class="card-toolbar">
      <a href="{{ route('student.index') }}" class="btn btn-light-primary font-weight-bolder mr-2">
        <i class="ki ki-long-arrow-back icon-sm"></i>
        Back
      </a>
      <div class="btn-group">
        <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder">
          <i class="ki ki-check icon-sm"></i>
          Save Form
        </button>
      </div>
    </div>
  </div>
  <div class="card-body">
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <!--begin::Form-->
    <form class="form" id="kt_form" method="post" action="{{ route('student.store') }}" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col-xl-2"></div>
        <div class="col-xl-8">
          <div class="my-5">


            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="name">Name&nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="name" id="name" value="{{ old('name') }}"
                  class="form-control form-control-solid @error('name') is-invalid @enderror" type="text" required>
                @error('name')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="roll">Roll &nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="roll" id="roll" value="{{ old('roll') }}"
                  class="form-control form-control-solid @error('roll') is-invalid @enderror" type="number" required>
                @error('roll')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="reg">Registration Num &nbsp;<span
                  class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="reg" id="reg" value="{{ old('reg') }}"
                  class="form-control form-control-solid @error('reg') is-invalid @enderror" type="number" required>
                @error('reg')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="session">Session &nbsp;<span
                  class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="session" id="session" value="{{ old('session') }}" placeholder="17-18"
                  class="form-control form-control-solid @error('session') is-invalid @enderror" type="text" required>
                @error('session')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="section_id">Select Section<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="section_id" name="section_id">
                  @foreach ($sections as $section)
                  <option value="{{ $section->id }}">
                    {{ $section->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="shift_id">Select Shift<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="shift_id" name="shift_id">
                  @foreach ($shifts as $shift)
                  <option value="{{ $shift->id }}">
                    {{ $shift->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="semester_id">Select Semester<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="semester_id" name="semester_id">
                  @foreach ($semesters as $semester)
                  <option value="{{ $semester->id }}">
                    {{ $semester->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="department_id">Select Department<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="department_id" name="department_id">
                  @foreach ($departments as $department)
                  <option value="{{ $department->id }}">
                    {{ $department->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>

          </div>
        </div>
        <div class="col-xl-2"></div>
      </div>
    </form>
  </div>
</div>

@endsection

resources/views/dashboard/student/edit.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="card card-custom card-sticky" id="kt_page_sticky_card">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">
        Edit Student
      </h3>
    </div>
    <div class="card-toolbar">
      <a href="{{ route('student.index') }}" class="btn btn-light-primary font-weight-bolder mr-2">
        <i class="ki ki-long-arrow-back icon-sm"></i>
        Back
      </a>
      <div class="btn-group">
        <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder">
          <i class="ki ki-check icon-sm"></i>
          Update Form
        </button>
      </div>
    </div>
  </div>
  <div class="card-body">

    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <!--begin::Form-->
    <form class="form" id="kt_form" method="post" action="{{ route('student.update', $student->id) }}"
      enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col-xl-2"></div>
        <div class="col-xl-8">
          <div class="my-5">


            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="name">Name&nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="name" id="name" value="{{ old('name', $student->name) }}"
                  class="form-control form-control-solid @error('name') is-invalid @enderror" type="text" required>
                @error('name')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="roll">Roll &nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="roll" id="roll" value="{{ old('roll', $student->roll) }}"
                  class="form-control form-control-solid @error('roll') is-invalid @enderror" type="number" required>
                @error('roll')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="reg">Registration Num &nbsp;<span
                  class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="reg" id="reg" value="{{ old('reg', $student->reg) }}"
                  class="form-control form-control-solid @error('reg') is-invalid @enderror" type="number" required>
                @error('reg')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>

            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="session">Session &nbsp;<span
                  class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="session" id="session" value="{{ old('session', $student->session) }}"
                  class="form-control form-control-solid @error('session') is-invalid @enderror" type="text" required>
                @error('session')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="section_id">Select Section<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="section_id" name="section_id">
                  @foreach ($sections as $section)
                  <option value="{{ $section->id}}"  {{ ($result->section->id == $section->id) ? 'selected' : null }} >
                    {{ $section->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="shift_id">Select Shift<span class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="shift_id" name="shift_id">
                  @foreach ($shifts as $shift)
                  <option value="{{ $shift->id}}"   {{ ($result->shift->id == $shift->id) ? 'selected' : null }}>
                    {{ $shift->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="semester_id">Select Semester<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="semester_id" name="semester_id">
                  @foreach ($semesters as $semester)
                  <option value="{{ $semester->id }}"   {{ ($result->semester->id == $semester->id) ? 'selected' : null }} >
                    {{ $semester->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="department_id">Select Department<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="department_id" name="department_id">
                  @foreach ($departments as $department)
                  <option value="{{ $department->id}}"   {{  ($result->department->id == $department->id) ? 'selected' : null }} >
                    {{ $department->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>

          </div>
        </div>
        <div class="col-xl-2"></div>
      </div>
    </form>
    <!--end::Form-->
  </div>
</div>

@endsection

resources/views/dashboard/student/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="card card-custom">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Student List</h3>
            </div>
            <div class="card-toolbar">
                @can('web_content.create')
                    <a href="{{ route('student.create') }}" class="btn btn-primary font-weight-bolder">
                        <span class="svg-icon svg-icon-md">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect x="0" y="0" width="24" height="24"></rect>
                                    <circle fill="#000000" cx="9" cy="15" r="6"></circle>
                                    <path
                                        d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z"
                                        fill="#000000" opacity="0.3"></path>
                                </g>
                            </svg>
                        </span>
                        Add Student
                    </a>
                @endcan
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
                    <thead>
                        <tr>
                            <th>SL</th>
                            <th>Name</th>
                            <th>Roll</th>
                            <th>Registration</th>
                            <th>Department</th>
                            <th>Semester</th>
                            <th>Section</th>
                            <th>Shift</th>
                            <th>Session</th>
                            {{-- <th>Message</th> --}}
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($students as $student)
                            <tr>
                                <td>
                                    {{ $student->sl }}
                                </td>
                                <td>
                                    {{ $student->name }}
                                </td>
                                <td>
                                    {{ $student->roll }}
                                </td>
                                <td>
                                    {{ $student->reg }}
                                </td>
                                <td>
                                    {{ $student->department->name }}
                                </td>
                                <td>
                                    {{ $student->semester->name }}
                                </td>
                                <td>
                                    {{ $student->section->name }}
                                </td>
                                <td>
                                    {{ $student->shift->name }}
                                </td>
                                <td>
                                    {{ $student->session }}
                                </td>
                                {{-- <td>
                                    {{ $student->message }}
                                </td> --}}
                                <td nowrap="nowrap">
                                    @can('web_content.edit')
                                        <a href="{{ route('student.edit', $student->id) }}" class="btn btn-icon btn-light btn-hover-primary btn-sm mr-2">
                                            <span class="svg-icon svg-icon-md svg-icon-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                        <rect x="0" y="0" width="24" height="24"></rect>
                                                        <path
                                                            d="M12.2674799,18.2323597 L12.0084872,5.45852451 C12.0004303,5.06114792 12.1504154,4.6768183 12.4255037,4.38993949 L15.0030167,1.70195304 L17.5910752,4.40093695 C17.8599071,4.6812911 18.0095067,5.05499603 18.0083938,5.44341307 L17.9718262,18.2062508 C17.9694575,19.0329966 17.2985816,19.701953 16.4718324,19.701953 L13.7671717,19.701953 C12.9505952,19.701953 12.2840328,19.0487684 12.2674799,18.2323597 Z"
                                                            fill="#000000" fill-rule="nonzero" transform="translate(14.701953, 10.701953) rotate(-135.000000) translate(-14.701953, -10.701953)"></path>
                                                        <path
                                                            d="M12.9,2 C13.4522847,2 13.9,2.44771525 13.9,3 C13.9,3.55228475 13.4522847,4 12.9,4 L6,4 C4.8954305,4 4,4.8954305 4,6 L4,18 C4,19.1045695 4.8954305,20 6,20 L18,20 C19.1045695,20 20,19.1045695 20,18 L20,13 C20,12.4477153 20.4477153,12 21,12 C21.5522847,12 22,12.4477153 22,13 L22,18 C22,20.209139 20.209139,22 18,22 L6,22 C3.790861,22 2,20.209139 2,18 L2,6 C2,3.790861 3.790861,2 6,2 L12.9,2 Z"
                                                            fill="#000000" fill-rule="nonzero" opacity="0.3"></path>
                                                    </g>
                                                </svg>
                                            </span>
                                        </a>
                                    @endcan
                                    @can('web_content.delete')
                                        <form method="post" action="{{ route('student.destroy', $student->id) }}" class="d-inline-block">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" onclick="return confirm('Are you sure you want to delete this item?');" class="btn btn-icon btn-light btn-hover-primary btn-sm">
                                                <span class="svg-icon svg-icon-md svg-icon-primary">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                            <rect x="0" y="0" width="24" height="24"></rect>
                                                            <path d="M6,8 L6,20.5 C6,21.3284271 6.67157288,22 7.5,22 L16.5,22 C17.3284271,22 18,21.3284271 18,20.5 L18,8 L6,8 Z" fill="#000000"
                                                                fill-rule="nonzero"></path>
                                                            <path
                                                                d="M14,4.5 L14,4 C14,3.44771525 13.5522847,3 13,3 L11,3 C10.4477153,3 10,3.44771525 10,4 L10,4.5 L5.5,4.5 C5.22385763,4.5 5,4.72385763 5,5 L5,5.5 C5,5.77614237 5.22385763,6 5.5,6 L18.5,6 C18.7761424,6 19,5.77614237 19,5.5 L19,5 C19,4.72385763 18.7761424,4.5 18.5,4.5 L14,4.5 Z"
                                                                fill="#000000" opacity="0.3"></path>
                                                        </g>
                                                    </svg>
                                                </span>
                                            </button>
                                        </form>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $students->links() }}
            </div>
        </div>
    </div>

@endsection