routes/web.php
<?php

use App\Http\Controllers\MainResultController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Controllers\FormController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\Admin\FaqController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\Admin\NoticeController;
use App\Http\Controllers\Website\HomeController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Website\ContactMessageController;
use Spatie\MediaLibrary\MediaCollections\Models\Media as MediaAlias;

// cache clear
Route::get('reboot', function () {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    dd('Done');
});
Route::get('storageLink', function () {
    Artisan::call('storage:link');
    dd('Done');
});
Route::get('migrate', function () {
    Artisan::call('migrate');
    dd('Done');
});

Route::get('migrate-seed', function () {
    Artisan::call('migrate:fresh --seed');
    dd('Done');
});

Route:: middleware('web')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::post('result/search',[HomeController::class,'result'])->name('result.search');
});

Route::prefix('dashboard')->middleware(['auth', 'verified'])->group(function () {
    Route::view('/', 'dashboard.dashboard')->name('dashboard');
    Route::resource('user', UserController::class);
    Route::resource('faq', FaqController::class)->except('index', 'show');
    Route::resource('contact-message', ContactMessageController::class)->except(['show', 'create', 'edit', 'update']);
    Route::resource('notice', NoticeController::class)->except('show');
    Route::resource('form', FormController::class)->except('show');
    Route::resource('student', StudentController::class)->except('show');
    Route::resource('subject', SubjectController::class)->except('show');
    Route::resource('department', DepartmentController::class)->except('show');
    Route::resource('result', ResultController::class)->except('show');
    Route::get('result/particular', [ResultController::class, 'particular'])->name('result.particular');
    Route::post('result/particularData',[ResultController::class,'particularData'])->name('result.particularData');
    Route::post('result/dataStore',[ResultController::class,'dataStore'])->name('result.dataStore');

//    Main Results
    Route::get('mainResult',[MainResultController::class,'index'])->name('mainResult.index');
    Route::get('mainResult/search',[MainResultController::class,'search'])->name('mainResult.search');
    Route::post('mainResult/result',[MainResultController::class,'result'])->name('mainResult.result');

    Route::get('change_password', [UserController::class, 'change_password'])->name('change_password');
    Route::get('settings/company_settings', [SettingController::class, 'editCompanySetting'])->name('company.edit');
    Route::post('settings/company_setting', [SettingController::class, 'updateCompanySetting'])->name('company.update');

    Route::delete('remove-media/{media}', function (MediaAlias $media) {
        $media->delete();
        return back()->with('success', 'Media successfully deleted.');
    })->name('remove-media');

    // Role Permission
    Route::resource('developer/permission', PermissionController::class)->only('index', 'store');
    Route::get('role/assign', [RoleController::class, 'roleAssign'])->name('role.assign');
    Route::post('role/assign', [RoleController::class, 'storeAssign'])->name('store.assign');
    Route::resource('role', RoleController::class);
});

app/Models/MainResult.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MainResult extends Model
{
    use HasFactory;

    protected $fillable = [
        'student_id',
        'semester_id',
        'grade',
        'fail',
        'total_point',
    ];

    public function student()
    {
        return $this->belongsTo(Student::class);
    }

    public function semester()
    {
        return $this->belongsTo(Semester::class);
    }
}

app/Http/Controllers/MainResultController.php
<?php

namespace App\Http\Controllers;

use App\Models\Department;
use App\Models\MainResult;
use App\Models\Semester;
use App\Models\Student;
use App\Models\Subject;
use Illuminate\Http\Request;

class MainResultController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $this->checkPermission('result.access');

        $mainResults = MainResult::with(['student','semester'])->paginate($this->itemPerPage);
        $this->putSL($mainResults);
        return view('dashboard.mainResult.index', compact('mainResults'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search()
    {
        $semesters      =Semester::get();
        $departments    =Department::get();
        return view('dashboard.mainResult.search',compact('semesters','departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function result(Request $request)
    {
        $student=Student::where('department_id',$request->department_id)
            ->where('roll',$request->roll)
            ->where('reg',$request->reg)
            ->first();

        $mainResult= MainResult::where('semester_id',$request->semester_id)
            ->where('student_id',$student->id)
            ->first();
        return view('dashboard.mainResult.result', compact('mainResult'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\MainResult  $mainResult
     * @return \Illuminate\Http\Response
     */
    public function show(MainResult $mainResult)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\MainResult  $mainResult
     * @return \Illuminate\Http\Response
     */
    public function edit(MainResult $mainResult)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\MainResult  $mainResult
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, MainResult $mainResult)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\MainResult  $mainResult
     * @return \Illuminate\Http\Response
     */
    public function destroy(MainResult $mainResult)
    {
        //
    }
}

resources/views/dashboard/mainResult/edit.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="card card-custom card-sticky" id="kt_page_sticky_card">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">
        Edit Result
      </h3>
    </div>
    <div class="card-toolbar">
      <a href="{{ route('result.index') }}" class="btn btn-light-primary font-weight-bolder mr-2">
        <i class="ki ki-long-arrow-back icon-sm"></i>
        Back
      </a>
      <div class="btn-group">
        <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder">
          <i class="ki ki-check icon-sm"></i>
          Update Form
        </button>
      </div>
    </div>
  </div>
  <div class="card-body">

    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <!--begin::Form-->
    <form class="form" id="kt_form" method="post" action="{{ route('result.update', $result->id) }}"
      enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col-xl-2"></div>
        <div class="col-xl-8">
          <div class="my-5">

            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="student_id">Select Student<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="student_id" name="student_id">
                  @foreach ($students as $student)
                  <option value="{{ $student->id }}"   {{ ($result->$student->id == $student->id) ? 'selected' : null }}$student>
                    {{ $student->name }} ({{ $student->roll }})
                  </option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="semester_id">Select Semester<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="semester_id" name="semester_id">
                  @foreach ($semesters as $semester)
                  <option value="{{ $semester->id }}"  {{ ($result->semester->id == $semester->id) ? 'selected' : null }}>
                    {{ $semester->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="subject_id">Select Subject<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="subject_id" name="subject_id">
                  @foreach ($subjects as $subject)
                  <option value="{{ $subject->id }}"  {{ ($result->subject->id == $subject->id) ? 'selected' : null }}>
                    {{ $subject->name }} ({{ $subject->subject_code }})
                  </option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="tc">TC Number&nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="tc" id="tc" value="{{ old('tc', $result->tc) }}"
                  class="form-control form-control-solid @error('tc') is-invalid @enderror" type="number" >
                @error('tc')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="pc">PC Number&nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="pc" id="pc" value="{{ old('pc', $result->pc) }}"
                  class="form-control form-control-solid @error('pc') is-invalid @enderror" type="number" >
                @error('pc')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="tf">TF Number&nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="tf" id="tf" value="{{ old('tf', $result->tf) }}"
                  class="form-control form-control-solid @error('tf') is-invalid @enderror" type="number" >
                @error('tf')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="pf">PF Number&nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="pf" id="pf" value="{{ old('pf', $result->pf) }}"
                  class="form-control form-control-solid @error('pf') is-invalid @enderror" type="number" >
                @error('pf')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>

          </div>
        </div>
        <div class="col-xl-2"></div>
      </div>
    </form>
    <!--end::Form-->
  </div>
</div>

@endsection

resources/views/dashboard/mainResult/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="card card-custom">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Main Result List</h3>
            </div>
            <div class="card-toolbar">
{{--                @can('web_content.create')--}}
{{--                    <a href="{{ route('mainResult.create') }}" class="btn btn-primary font-weight-bolder">--}}
{{--                        <span class="svg-icon svg-icon-md">--}}
{{--                            <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">--}}
{{--                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">--}}
{{--                                    <rect x="0" y="0" width="24" height="24"></rect>--}}
{{--                                    <circle fill="#000000" cx="9" cy="15" r="6"></circle>--}}
{{--                                    <path--}}
{{--                                        d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z"--}}
{{--                                        fill="#000000" opacity="0.3"></path>--}}
{{--                                </g>--}}
{{--                            </svg>--}}
{{--                        </span>--}}
{{--                        Add Result--}}
{{--                    </a>--}}
{{--                @endcan--}}
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
                    <thead>
                        <tr>
                            <th>SL</th>
                            <th>Name</th>
                            <th>Roll</th>
                            <th>Semester</th>
                            <th>Grade</th>
                            <th>Total Point</th>
                            {{-- <th>Message</th> --}}
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($mainResults as $mainResult)

                            <tr>

                                <td>
                                    {{ $mainResult->sl }}
                                </td>
                                <td>
                                    {{ $mainResult->student->name }}
                                </td>
                                </td>
                                <td>
                                    {{ $mainResult->student->roll }}
                                </td>
                                <td>
                                    {{ $mainResult->semester->name }}
                                </td>
                                <td>
                                @if ( $mainResult->grade == "F" )

                                      <span class="label label-danger label-pill label-inline mr-2">{{ $mainResult->grade }}</span>({{ $mainResult->fail }})

                                @else
                                      <span class="label label-rounded label-success mr-2">{{ $mainResult->grade }}</span>
                                @endif
                                </td>

                                <td>
                                    {{ $mainResult->total_point }}
                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $mainResults->links() }}
            </div>
        </div>
    </div>

@endsection

resources/views/dashboard/mainResult/result.blade.php
@extends('layouts.dashboard')

@section('content')

  <div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
      <div class="card-title">
        <h3 class="card-label">Main Result List</h3>
      </div>
      <div class="card-toolbar">
        {{--                @can('web_content.create')--}}
        {{--                    <a href="{{ route('mainResult.create') }}" class="btn btn-primary font-weight-bolder">--}}
        {{--                        <span class="svg-icon svg-icon-md">--}}
        {{--                            <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">--}}
        {{--                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">--}}
        {{--                                    <rect x="0" y="0" width="24" height="24"></rect>--}}
        {{--                                    <circle fill="#000000" cx="9" cy="15" r="6"></circle>--}}
        {{--                                    <path--}}
        {{--                                        d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z"--}}
        {{--                                        fill="#000000" opacity="0.3"></path>--}}
        {{--                                </g>--}}
        {{--                            </svg>--}}
        {{--                        </span>--}}
        {{--                        Add Result--}}
        {{--                    </a>--}}
        {{--                @endcan--}}
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
          <thead>
          <tr>
            <th>Name</th>
            <th>Roll</th>
            <th>Semester</th>
            <th>Grade</th>
            <th>Total Point</th>
            {{-- <th>Message</th> --}}
          </tr>
          </thead>
          <tbody>

            <tr>
              <td>
                {{ $mainResult->student->name }}
              </td>
              </td>
              <td>
                {{ $mainResult->student->roll }}
              </td>
              <td>
                {{ $mainResult->semester->name }}
              </td>
              <td>
                @if ( $mainResult->grade == "F" )

                  <span class="label label-danger label-pill label-inline mr-2">{{ $mainResult->grade }}</span>({{ $mainResult->fail }})

                @else
                  <span class="label label-rounded label-success mr-2">{{ $mainResult->grade }}</span>
                @endif
              </td>

              <td>
                {{ $mainResult->total_point }}
              </td>

            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

@endsection

resources/views/dashboard/mainResult/search.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="card card-custom card-sticky" id="kt_page_sticky_card">
  <div class="card-header">
    <div class="card-title">
      <h3 class="card-label">
        Search Result
      </h3>
    </div>
    <div class="card-toolbar">
      <a href="{{ route('student.index') }}" class="btn btn-light-primary font-weight-bolder mr-2">
        <i class="ki ki-long-arrow-back icon-sm"></i>
        Back
      </a>
      <div class="btn-group">
        <button type="submit" form="kt_form" class="btn btn-primary font-weight-bolder">
          <i class="ki ki-check icon-sm"></i>
          Save Form
        </button>
      </div>
    </div>
  </div>
  <div class="card-body">
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <!--begin::Form-->
    <form class="form" id="kt_form" method="post" action="{{ route('mainResult.result') }}" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col-xl-2"></div>
        <div class="col-xl-8">
          <div class="my-5">


            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="department_id">Select Department<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="department_id" name="department_id">
                  @foreach ($departments as $department)
                    <option value="{{ $department->id }}">
                      {{ $department->name }}
                    </option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="form-group row">
              <label class="col-lg-3 col-form-label" for="semester_id">Select Semester<span
                  class="text-danger">*</span></label>
              <div class="col-lg-9">
                <select class="form-control select2" id="semester_id" name="semester_id">
                  @foreach ($semesters as $semester)
                  <option value="{{ $semester->id }}">
                    {{ $semester->name }}
                  </option>
                  @endforeach
                </select>
              </div>
            </div>


            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="roll">Roll&nbsp;Num<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="roll" id="roll" value="{{ old('roll') }}"
                  class="form-control form-control-solid @error('roll') is-invalid @enderror" type="number" >
                @error('roll')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>
            <div class="form-group row">
              <label class="col-md-3 col-form-label" for="reg">Resgistration Num&nbsp;<span class="text-danger">*</span></label>
              <div class="col-md-9">
                <input name="reg" id="reg" value="{{ old('reg') }}"
                  class="form-control form-control-solid @error('reg') is-invalid @enderror" type="number" >
                @error('reg')
                <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
            </div>

          </div>
        </div>
        <div class="col-xl-2"></div>
      </div>
    </form>
  </div>
</div>

@endsection